In [1]:
# Import all dependencies and libraries
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
# declare an envirnment
env = gym.make("FrozenLake-v1")

In [5]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
#Initiate all the parameters needed for this game
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [13]:
# Algorithm implementation
reward_all_episodes = []

# Q-Learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    reward_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        # Exploration and Exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table for Q(s, a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        
        reward_current_episode += reward
        
        if done == True:
            break
            
    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    reward_all_episodes.append(reward_current_episode)

In [20]:
# Calculate and print average reward per thousand episode

rewards_per_thousand_episodes = np.split(np.array(reward_all_episodes), num_episodes/1000)
count = 1000

print(">>>>>>>>> Average Reward Per Thoursand Episodes <<<<<<<<\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    
print("\n\n >>>>>>>>>> Q-table <<<<<<<<<\n")
print(q_table)

>>>>>>>>> Average Reward Per Thoursand Episodes <<<<<<<<

1000 :  0.06100000000000005
2000 :  0.22800000000000017
3000 :  0.3840000000000003
4000 :  0.5680000000000004
5000 :  0.6520000000000005
6000 :  0.6480000000000005
7000 :  0.6840000000000005
8000 :  0.7130000000000005
9000 :  0.6850000000000005
10000 :  0.6780000000000005


 >>>>>>>>>> Q-table <<<<<<<<<

[[0.59548826 0.50995967 0.50487605 0.50444674]
 [0.31731065 0.30852286 0.36924074 0.5448295 ]
 [0.40561606 0.41900219 0.41649117 0.48730389]
 [0.3857789  0.31957766 0.23353449 0.45297862]
 [0.61497795 0.33766035 0.41045515 0.2627203 ]
 [0.         0.         0.         0.        ]
 [0.45551032 0.18674701 0.21116509 0.19618233]
 [0.         0.         0.         0.        ]
 [0.40442511 0.49349631 0.42951305 0.63970008]
 [0.44017186 0.68579101 0.44589377 0.43233372]
 [0.6679334  0.32689373 0.42246124 0.31471961]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.57626552 0.4997485  0

In [21]:
# Agent play three episode using knowledge gained from the training

for episode in range(3):
    state = env.reset()
    done = False
    print("<<<<Episode: ", episode+1, ">>>>>>\n\n")
    time.sleep(1)
    
    for steps in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print(">>>>> You reached the goal <<<<<")
                time.sleep(3)
            else:
                print(">>>>>>You fell through into a hole<<<<<<")
                time.sleep(3)
            clear_output(wait=True)
            break
        state = new_state
env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG
>>>>>>You fell through a hole<<<<<<
